### ISSUE TITLE
Need to indicate whether Gluster nodes are used for other purposes

### ISSUE THREAD

**Issue by alanbchristie** [InformaticsMatters/okd-orchestrator#44]
AT the moment the templating assumes the Gluster nodes will be independent of the compute nodes. So the resulting inventory file contains duplicate definitions under the `nodes:` block.

Also the nodes appear to have an infra-compute label and should probably just have a generic `compute` label.

```
        nodes:
          hosts:
            xchem-master-1.novalocal:
              openshift_node_group_name: 'node-config-master-compute'
            xchem-infra-1.novalocal:
              openshift_node_group_name: 'node-config-infra-compute'
            xchem-graph-001.novalocal:
              openshift_node_group_name: 'node-config-graph'
            xchem-app-001.novalocal:
              openshift_node_group_name: 'node-config-app'
            xchem-gpu-001.novalocal:
              openshift_node_group_name: 'node-config-gpu'
            xchem-infra-1.novalocal:
              openshift_node_group_name: 'node-config-infra-compute'
            xchem-graph-001.novalocal:
              openshift_node_group_name: 'node-config-infra-compute'
            xchem-app-001.novalocal:
              openshift_node_group_name: 'node-config-infra-compute'
```
